sources:
- hass:
    url: "ws://your.HASS.API.URL.here"
    auth_token: "your_token_here"
    plugs:
        # Scaled attribute (dimmer setting) example
        - Kitchen_Lights:
            alias: "Kitchen Lights"
            entity_id: light.kitchen_main_lights
            mac: 53:75:31:f6:4b:01
            off_usage: 0
            min_watts: 0
            max_watts: 42
            attribute_min: 0
            attribute_max: 255
            attribute: brightness
            off_state_value: off

        # Direct power usage reporting example
        - Pump_Power_Meter:
            alias: "Sump Pump Power Meter"
            entity_id: sensor.sump_pump
            mac: 53:75:31:f6:4b:02
            # Or, if the power usage value is buried in the state update, something like:
            # power_keypath: "state/usage/power"

        # Example with an "off" vampire consumption
        - Outdoor_Lights:
            alias: "Outdoor Lights"
            entity_id: light.outdoor_deck_lights
            mac: 53:75:31:f6:4b:03
            off_usage: 4  # Represents a vampire load when "off"
            min_watts: 10
            max_watts: 60
            attribute_min: 0
            attribute_max: 255
            attribute: brightness
            off_state_value: off

        # Binary on/off state-based usage device
        - Dehumidifier:
            alias: "Dehumidifier"
            entity_id: switch.dehumidifier
            mac: 53:75:31:f6:4b:04
            off_usage: 0
            max_watts: 42  # Wattage used for 'on' state
            on_state_value: "on"
            off_state_value: "off"
- hass:
    url: "ws://your.HASS.API.URL.here"
    auth_token: "your_token_here"
    plugs:
        # Scaled attribute (dimmer setting) example
        - Kitchen_Lights:
            alias: "Kitchen Lights"
            entity_id: light.kitchen_main_lights
            mac: 53:75:31:f6:4b:01
            off_usage: 0
            min_watts: 0
            max_watts: 42
            attribute_min: 0
            attribute_max: 255
            attribute: brightness
            off_state_value: off

        # Direct power usage reporting example
        - Pump_Power_Meter:
            alias: "Sump Pump Power Meter"
            entity_id: sensor.sump_pump
            mac: 53:75:31:f6:4b:02
            # Or, if the power usage value is buried in the state update, something like:
            # power_keypath: "state/usage/power"

        # Example with an "off" vampire consumption
        - Outdoor_Lights:
            alias: "Outdoor Lights"
            entity_id: light.outdoor_deck_lights
            mac: 53:75:31:f6:4b:03
            off_usage: 4  # Represents a vampire load when "off"
            min_watts: 10
            max_watts: 60
            attribute_min: 0
            attribute_max: 255
            attribute: brightness
            off_state_value: off
- mqtt:
    host: "your.mqtt.broker"
    port: 1883       # Optional
    username: admin  # Optional
    password: supersecret1  # Optional
    plugs:
        # Direct power reporting example
        - UPS:
            alias: "UPS Backup"
            power_topic: "ups/usage"  # Value at this topic should be numeric and units of watts!
            state_topic: "ups/state"
            off_state_value: "OFF"
            off_value: 0   # Optional, set to non-zero for vampire loads
        # Scaled attribute (dimmer setting) example
        - Porch_Light:
            alias: "Back Porch Light"
            attribute_topic: "lights/porch/brightness"
            attribute_min: 0
            attribute_max: 255
            min_watts: 0
            max_watts: 120
        # State embedded in JSON value
        # Use if the MQTT topic returns a JSON dict instead of a single value
        - LED_Strip:
            alias: "TV LED Strips"
            attribute_topic: "leds/living_room_tv/state"
            attribute_topic_keypath: "settings/brightness"  # Ex: if value at topic were {"settings":{"color":"red", "brightness": 75}}
            attribute_min: 0
            attribute_max: 100
            min_watts: 0
            max_watts: 15

  - static:
      plugs:
      - NAS:
          mac: 53:75:31:f6:4c:01
          max_watts: 15
          alias: "NAS Server"
      - Fan:
          mac: 53:75:31:f6:4c:02
          max_watts: 5
          alias: "Ceiling Fan"